name: Generate Private Repo Stats

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install requests pillow

      - name: Run Python script
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
        run: python scripts/generate_stats_image.py

      - name: Commit and push image
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add stats_output/myprojects2022_stats.png
          git commit -m "Update private repo stats image"
          git push
